# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qgis2UrscapeUI
                                 A QGIS plugin
 This plugin provides a GUI for qgis2urscape.py
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-05
        copyright            : (C) 2020 by Muhammad Salihin Bin Zaol-kefli
        email                : muhammad.zaolkefli@sec.ethz.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qgis2UrscapeUI class from file Qgis2UrscapeUI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgis2urscapeUI import Qgis2UrscapeUI
    return Qgis2UrscapeUI(iface)
